name: CI

on: [ push, pull_request ]

jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        image:
          - "ubuntu:20.04"        # gcc  9.3.0, clang 10.0.0, cmake 3.16.3
          - "ubuntu:22.04"        # gcc 12.2.0, clang 15.0.7, cmake 3.24.2
          - "ubuntu:24.04"        # gcc 14.2.0, clang 18.1.3, cmake 3.28.3
          - "debian:bullseye"     # gcc 10.2.1, clang 11.0.1, cmake 3.18.4
          - "debian:bookworm"     # gcc 12.2.0, clang 15.0.6, cmake 3.25.1
          - "debian:testing"
          - "debian:experimental"
          - "fedora:39"
          - "fedora:40"
          - "fedora:41"
        build_type: [Debug]
        cpp_compiler: [g++]
        include:
          - image: "debian:bookworm"
            c_compiler: clang
            cpp_compiler: clang++
          - image: "debian:bookworm"
            build_type: Release
          - image: "debian:bookworm"
            c_compiler: clang
            cpp_compiler: clang++
            data_view: std::string_view
          - image: "debian:testing"
            c_compiler: clang
            cpp_compiler: clang++
          - image: "debian:experimental"
            c_compiler: clang
            cpp_compiler: clang++
    container:
      image: ${{ matrix.image }}
      env:
        BUILD_TYPE: ${{ matrix.build_type }}
        CC: ${{ matrix.c_compiler }}
        CXX: ${{ matrix.cpp_compiler }}
        PROTOZERO_DATA_VIEW: ${{ matrix.data_view }}
        APT_LISTCHANGES_FRONTEND: none
        DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Prepare container (apt)
        shell: bash
        if: startsWith(matrix.image, 'debian:') || startsWith(matrix.image, 'ubuntu:')
        run: |
          apt-get update -qq
          apt-get install -y \
            clang \
            cmake \
            doxygen \
            g++ \
            git \
            graphviz \
            libboost-dev \
            make
      - name: Prepare container (dnf)
        shell: bash
        if: startsWith(matrix.image, 'fedora:')
        run: |
          dnf install --quiet --assumeyes \
            boost-devel \
            cmake \
            doxygen \
            gcc-c++ \
            git \
            graphviz \
            make
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/install-protozero
      - uses: ./.github/actions/cmake
      - uses: ./.github/actions/build
      - uses: ./.github/actions/ctest

  ubuntu-latest:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    env:
      CC: clang-18
      CXX: clang++-18
      BUILD_TYPE: Debug
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/install-protozero
      - uses: ./.github/actions/cmake
      - uses: ./.github/actions/build
      - uses: ./.github/actions/ctest

  macos:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - macos-15
        build_type: [Debug]
        include:
          - os: macos-15
            build_type: Release
    env:
      CC: clang
      CXX: clang++
      BUILD_TYPE: ${{ matrix.build_type }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/install-protozero
      - uses: ./.github/actions/install-macos
      - uses: ./.github/actions/cmake
      - uses: ./.github/actions/build
      - uses: ./.github/actions/ctest

  windows:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2019
          - windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/install-protozero
      - uses: ./.github/actions/install-windows
      - uses: ./.github/actions/cmake-windows
      - uses: ./.github/actions/build
      - uses: ./.github/actions/ctest
